platform :ios, '9.0'

target 'ArticleFeed' do
  use_frameworks!

  # Architecture
  pod 'ReactorKit', :git => 'https://github.com/ReactorKit/ReactorKit.git', :branch => 'swift-4.0'
  pod 'SectionReactor', :path => '../../SectionReactor.podspec'

  # Rx
  pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'rxswift4.0-swift4.0'
  pod 'RxCocoa', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'rxswift4.0-swift4.0'
  pod 'RxDataSources', :git => 'https://github.com/RxSwiftCommunity/RxDataSources.git', :branch => 'swift4.0'
  pod 'Differentiator', :git => 'https://github.com/RxSwiftCommunity/RxDataSources.git', :branch => 'swift4.0'
  pod 'RxViewController'

  # Misc.
  pod 'Then'
  pod 'ManualLayout'
  pod 'SnapKit'
  pod 'ReusableKit'
  pod 'UICollectionViewFlexLayout'
  pod 'CGFloatLiteral'
  pod 'SwiftyColor'
  pod 'LoremIpsum'
end
